### ISSUE TITLE
Error installing Walle Python SDK under Divio

### ISSUE THREAD

**Issue by miguelsdl** [wallee-payment/python-sdk#1]
Can you help me with ?
root@c806add2de40:/app# pip install --upgrade wallee
Looking in indexes: https://wheels.aldryn.net/v1/aldryn-extras+pypi/aldryn-baseproject-v4-py36/+simple/
Collecting wallee
  Using cached https://wheels-cdn.aldryn.net/pypi/aldryn-baseproject-v4-py36/wallee/2.0.0/1571062149/51453e6658c002daebf54eb4d5ff7874/wallee-2.0.0-py3-none-any.whl
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from wallee) (2019.6.16)
Requirement already satisfied, skipping upgrade: urllib3>=1.23 in /usr/local/lib/python3.6/site-packages (from wallee) (1.25.3)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /usr/local/lib/python3.6/site-packages (from wallee) (2.8.0)
Requirement already satisfied, skipping upgrade: six>=1.10 in /usr/local/lib/python3.6/site-packages (from wallee) (1.12.0)
Collecting enum34>=1.1.6
  Using cached https://wheels.aldryn.net/v1/pypi/aldryn-baseproject-v4-py36/%2Bsimple/enum34/1.1.6/download/89931/enum34-1.1.6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_xen8sum/enum34/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_xen8sum/enum34/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-_xen8sum/enum34/pip-egg-info
         cwd: /tmp/pip-install-_xen8sum/enum34/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 6, in <module>
        import distutils.core
      File "/usr/local/lib/python3.6/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/usr/local/lib/python3.6/distutils/dist.py", line 9, in <module>
        import re
      File "/usr/local/lib/python3.6/re.py", line 142, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
root@c806add2de40:/app# python -V
Python 3.6.8
root@c806add2de40:/app#

**Comment by vttn** [comment]
Unfortunately I am unable to reproduce the issue. Since it looks like the issue is with the python enum34 library. I suggest that you install the enum library manually via `pip install enum34>=1.1.6`.

Please share the result. Can you also please show me the output of `pip freeze` and `pip -V` from your environment.

If you are using a dockerized environment, please share it with me so that I can try to reproduce the issue you are facing.

**Comment by miguelsdl** [comment]
WTF: Saquenme de esta lista de email que yo no tengo nada que ver. miren
bien a quien copian
