### ISSUE TITLE
Documentation lack!!!

### ISSUE THREAD

**Issue by djeck1432** [wallee-payment/python-sdk#3]
Hello, I see, you created a big wonderful project, but I cannot  find any examples or descriptions about how it should be properly integrate. I have written to your support, but nothing! I would be lovely to help you with that, but please give me a response, How I can integrate. You have a lot of ifs and strategies but no one good described example. 

Thank you)

**Comment by thomashunziker** [comment]
Thank you for getting back to us.

You find on the main page of the repository an example: https://github.com/wallee-payment/python-sdk

Furthermore you can find also some tests here:
https://github.com/wallee-payment/python-sdk/tree/master/test

**Comment by djeck1432** [comment]
> Thank you for getting back to us.
> 
> You find on the main page of the repository an example: https://github.com/wallee-payment/python-sdk
> 
> Furthermore you can find also some tests here:
> https://github.com/wallee-payment/python-sdk/tree/master/test

Hello, thank you for response.
I checked it in the beginning. There is no full example about one of your strategies, like `subscription`, different `ChargeFlow`, `Subscriber` and other stuff. And I understand, you are a new service and google doesn't find any information/example about integration. Maybe we can cooperate and write it together.
