### ISSUE TITLE
python 3.9 support

### ISSUE THREAD

**Issue by agitator** [wallee-payment/python-sdk#4]
any plans for python 3.9 support?

**Comment by vttn** [comment]
Thank you for the heads up, we will let you know once we have released this.

**Comment by agitator** [comment]
on python 3.8 and 3.9 I get this error
```enum34 attributeerror module 'enum' has no attribute 'intflag'```

Removing enum34 from requirements would fix this package for 3.9/3.8.
enum is part of python3.4+ and imho is a backport for python2 series

a 3.0.1 would be easy ;-)

**Comment by vttn** [comment]
Hello @agitator 

Thanks for the heads up.

We will look out for this during the Python 3.9 support work.

Regards,

Victor

**Comment by vttn** [comment]
We have added support for python 3.9. 

Unfortunately we can not reproduce the enum34 error in our tests.

**Comment by agitator** [comment]
installation/deployment is done with https://pypi.org/project/zc.buildout/ 
Anyway enum34 is "Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4" https://pypi.org/project/enum34/
and not needed if you support py 3.5 and up in https://github.com/wallee-payment/python-sdk/blob/master/setup.py#L39
